import { Redirect, router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PrimaryButton } from '@/components/ui/PrimaryButton';
import { colors, spacing } from '@/constants/theme';
import { useAuth } from '@/features/auth/AuthProvider';

function Stat({ value, label }: { value: number; label: string }) { return <View style={styles.stat}><Text style={styles.statValue}>{value.toLocaleString()}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
function Menu({ label, onPress }: { label: string; onPress?: () => void }) { return <Pressable accessibilityRole="button" onPress={onPress} style={styles.menu}><Text style={styles.menuLabel}>{label}</Text><Text style={styles.chevron}>›</Text></Pressable>; }

export default function MyPageScreen() {
  const { status, profile, signOut } = useAuth(); const [loading, setLoading] = useState(false);
  if (status === 'unauthenticated') return <Redirect href="/login" />;
  if (!profile) return null;
  const logout = () => Alert.alert('로그아웃할까요?', '다시 이용하려면 로그인이 필요해요.', [{ text: '취소', style: 'cancel' }, { text: '로그아웃', style: 'destructive', onPress: async () => { setLoading(true); try { await signOut(); router.replace('/login'); } finally { setLoading(false); } } }]);
  return <SafeAreaView edges={['top', 'left', 'right']} style={styles.safe}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.title}>마이페이지</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>🐾</Text></View><View style={styles.profileCopy}><Text style={styles.name}>{profile.name}</Text><Text style={styles.email}>{profile.email}</Text></View></View><View style={styles.petCard}><View><Text style={styles.cardEyebrow}>나의 반려동물</Text><Text style={styles.petName}>{profile.pet ? profile.pet.name : '반려동물을 등록해 주세요'}</Text>{profile.pet ? <Text style={styles.petMeta}>{profile.pet.breed} · {profile.pet.size === 'small' ? '소형견' : profile.pet.size === 'medium' ? '중형견' : '대형견'}</Text> : null}</View><Pressable onPress={() => router.push('/pet-profile')} style={styles.editButton}><Text style={styles.editLabel}>{profile.pet ? '수정' : '등록'}</Text></Pressable></View><View style={styles.points}><Text style={styles.cardEyebrow}>보유 포인트</Text><Text style={styles.pointValue}>{profile.pointBalance.toLocaleString()} P</Text><View style={styles.stats}><Stat value={profile.couponCount} label="쿠폰" /><Stat value={profile.badgeCount} label="배지" /><Stat value={profile.completedMissionCount} label="완료 미션" /><Stat value={profile.visitedRegionCount} label="방문 지역" /></View></View><View style={styles.menuGroup}><Menu label="포인트·쿠폰 내역" /><Menu label="획득 배지" /><Menu label="알림 설정" /><Menu label="개인정보 및 위치정보 설정" /><Menu label="고객센터" /></View><PrimaryButton label="로그아웃" variant="weak" loading={loading} onPress={logout} /><Pressable><Text style={styles.withdraw}>회원 탈퇴</Text></Pressable></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.canvas }, content: { padding: spacing.xl, paddingBottom: 56, gap: spacing.xl }, title: { color: colors.text, fontSize: 28, fontWeight: '800' }, profile: { flexDirection: 'row', alignItems: 'center', gap: spacing.lg }, avatar: { width: 64, height: 64, borderRadius: 24, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primaryWeak }, avatarText: { fontSize: 28 }, profileCopy: { flex: 1 }, name: { color: colors.text, fontSize: 21, fontWeight: '700' }, email: { marginTop: 4, color: colors.muted, fontSize: 14 }, petCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: spacing.lg, borderRadius: 20, backgroundColor: '#FFF2EA' }, cardEyebrow: { color: colors.body, fontSize: 13, fontWeight: '600' }, petName: { marginTop: 5, color: colors.text, fontSize: 18, fontWeight: '700' }, petMeta: { marginTop: 4, color: colors.body, fontSize: 13 }, editButton: { paddingHorizontal: 14, paddingVertical: 9, borderRadius: 12, backgroundColor: colors.surface }, editLabel: { color: colors.accent, fontWeight: '700' }, points: { padding: spacing.xl, borderRadius: 22, backgroundColor: colors.surface }, pointValue: { marginTop: spacing.sm, color: colors.primary, fontSize: 30, fontWeight: '800' }, stats: { flexDirection: 'row', marginTop: spacing.xl }, stat: { flex: 1, alignItems: 'center' }, statValue: { color: colors.text, fontSize: 16, fontWeight: '700' }, statLabel: { marginTop: 5, color: colors.muted, fontSize: 12 }, menuGroup: { overflow: 'hidden', borderRadius: 20, backgroundColor: colors.surface }, menu: { minHeight: 54, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.lg, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, menuLabel: { flex: 1, color: colors.text, fontSize: 15 }, chevron: { color: colors.muted, fontSize: 24 }, withdraw: { textAlign: 'center', color: colors.muted, fontSize: 13, textDecorationLine: 'underline' } });
