export const theme = {
  colors: {
    background: '#FFF9F5',
    cardBackground: '#FFFFFF',
    primary: '#F2B293',
    primaryStrong: '#A85335',
    primarySoft: '#FBECE3',
    onPrimary: '#3C2F2A',
    sage: '#C7D8C0',
    sageStrong: '#52684A',
    sageSoft: '#EEF3EA',
    sand: '#E6D7B8',
    sandStrong: '#78613C',
    sandSoft: '#F6F0E4',
    blue: '#CADCDF',
    blueStrong: '#496B72',
    blueSoft: '#EEF4F5',

    // Retain existing token names for callers while using the B1 palette.
    pastelYellow: '#E6D7B8',
    pastelSoftPink: '#FBECE3',
    pastelMint: '#C7D8C0',
    pastelPinkDark: '#A85335',
    pastelLavender: '#CADCDF',
    primaryMint: '#F2B293',
    primaryMintDark: '#A85335',
    pastelPink: '#F2B293',
    pastelPinkSoft: '#FBECE3',
    pastelMintSoft: '#EEF3EA',
    pastelPurple: '#CADCDF',
    pastelPurpleSoft: '#EEF4F5',

    textMain: '#3C2F2A',
    textSub: '#78675F',
    textLight: '#8C776C',
    border: '#EADDD4',
    divider: '#F0E5DE',
    selectedUnderline: '#A85335',
  },
  fontFamily: {
    regular: 'NanumSquareRound',
    bold: 'NanumSquareRoundB',
    extraBold: 'NanumSquareRoundEB',
  },
  shadows: {
    soft: {
      shadowColor: '#3C2F2A',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    gentle: {
      shadowColor: '#3C2F2A',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    floating: {
      shadowColor: '#3C2F2A',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 10,
      elevation: 6,
    },
  },
  borderRadius: {
    sm: 8,
    md: 14,
    lg: 20,
    xl: 26,
    full: 999,
  },
  typography: {
    title: {
      fontFamily: 'NanumSquareRound',
      fontSize: 26,
      fontWeight: '800' as const,
      color: '#3C2F2A',
      letterSpacing: -0.5,
    },
    subtitle: {
      fontFamily: 'NanumSquareRound',
      fontSize: 14,
      fontWeight: '500' as const,
      color: '#78675F',
      lineHeight: 20,
    },
    headerDate: {
      fontFamily: 'NanumSquareRound',
      fontSize: 22,
      fontWeight: '800' as const,
      color: '#3C2F2A',
      letterSpacing: 0.5,
      textTransform: 'uppercase' as const,
    },
    sectionTitle: {
      fontFamily: 'NanumSquareRound',
      fontSize: 17,
      fontWeight: '700' as const,
      color: '#3C2F2A',
    },
  },
};
