export const theme = {
  colors: {
    background: '#FAFAF6',
    cardBackground: '#FFFFFF',
    primary: '#769883',
    primaryStrong: '#456B54',
    primarySoft: '#EDF3EF',
    onPrimary: '#14231A',
    sage: '#C7D8C0',
    sageStrong: '#52684A',
    sageSoft: '#EEF3EA',
    sand: '#E6D7B8',
    sandStrong: '#78613C',
    sandSoft: '#F6F0E4',
    blue: '#CADCDF',
    blueStrong: '#496B72',
    blueSoft: '#EEF4F5',

    // Retain existing token names for callers while using the B1 palette.
    pastelYellow: '#E6D7B8',
    pastelSoftPink: '#EDF3EF',
    pastelMint: '#C7D8C0',
    pastelPinkDark: '#456B54',
    pastelLavender: '#CADCDF',
    primaryMint: '#769883',
    primaryMintDark: '#456B54',
    pastelPink: '#769883',
    pastelPinkSoft: '#EDF3EF',
    pastelMintSoft: '#EEF3EA',
    pastelPurple: '#CADCDF',
    pastelPurpleSoft: '#EEF4F5',

    textMain: '#26352C',
    textSub: '#68736C',
    textLight: '#68736C',
    border: '#DFE6DF',
    divider: '#E9EEE8',
    selectedUnderline: '#456B54',
  },
  fontFamily: {
    regular: 'NanumSquareRound',
    bold: 'NanumSquareRoundB',
    extraBold: 'NanumSquareRoundEB',
  },
  shadows: {
    soft: {
      shadowColor: '#26352C',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    gentle: {
      shadowColor: '#26352C',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    floating: {
      shadowColor: '#26352C',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.12,
      shadowRadius: 10,
      elevation: 6,
    },
  },
  borderRadius: {
    sm: 8,
    md: 14,
    lg: 20,
    xl: 26,
    full: 999,
  },
  typography: {
    title: {
      fontFamily: 'NanumSquareRound',
      fontSize: 26,
      fontWeight: '800' as const,
      color: '#26352C',
      letterSpacing: -0.5,
    },
    subtitle: {
      fontFamily: 'NanumSquareRound',
      fontSize: 14,
      fontWeight: '500' as const,
      color: '#68736C',
      lineHeight: 20,
    },
    headerDate: {
      fontFamily: 'NanumSquareRound',
      fontSize: 22,
      fontWeight: '800' as const,
      color: '#26352C',
      letterSpacing: 0.5,
      textTransform: 'uppercase' as const,
    },
    sectionTitle: {
      fontFamily: 'NanumSquareRound',
      fontSize: 17,
      fontWeight: '700' as const,
      color: '#26352C',
    },
  },
};
