import { router } from 'expo-router';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { FormField } from '@/components/ui/FormField';
import { PrimaryButton } from '@/components/ui/PrimaryButton';
import { colors, spacing } from '@/constants/theme';
import { useAuth } from '@/features/auth/AuthProvider';
import type { DogSize } from '@/types/user';

const sizes: { value: DogSize; label: string }[] = [{ value: 'small', label: '소형견' }, { value: 'medium', label: '중형견' }, { value: 'large', label: '대형견' }];
export default function PetProfileScreen() {
  const { profile, savePet } = useAuth(); const [name, setName] = useState(profile?.pet?.name ?? ''); const [breed, setBreed] = useState(profile?.pet?.breed ?? ''); const [birthDate, setBirthDate] = useState(profile?.pet?.birthDate ?? ''); const [size, setSize] = useState<DogSize>(profile?.pet?.size ?? 'small'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const submit = async () => { if (!name.trim()) { setError('반려동물 이름을 입력해 주세요.'); return; } setLoading(true); setError(''); try { await savePet({ name: name.trim(), breed: breed.trim(), size, birthDate: birthDate.trim() || undefined }); router.back(); } catch (caught) { setError(caught instanceof Error ? caught.message : '저장하지 못했어요.'); } finally { setLoading(false); } };
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.flex}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ 마이페이지</Text></Pressable><View><Text style={styles.title}>반려동물 프로필</Text><Text style={styles.subtitle}>장소 이용 조건과 맞춤 미션 추천에 활용돼요.</Text></View><View style={styles.form}><FormField label="이름" value={name} onChangeText={setName} placeholder="예: 보리" autoCapitalize="words" /><FormField label="견종" value={breed} onChangeText={setBreed} placeholder="예: 말티즈" autoCapitalize="words" /><View style={styles.sizeBlock}><Text style={styles.label}>크기</Text><View style={styles.sizeRow}>{sizes.map((item) => <Pressable key={item.value} onPress={() => setSize(item.value)} style={[styles.sizeButton, size === item.value && styles.sizeActive]}><Text style={[styles.sizeLabel, size === item.value && styles.sizeLabelActive]}>{item.label}</Text></Pressable>)}</View></View><FormField label="생년월일 (선택)" value={birthDate} onChangeText={setBirthDate} placeholder="YYYY-MM-DD" keyboardType="numbers-and-punctuation" />{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label="저장" loading={loading} onPress={() => void submit()} /></View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.canvas }, flex: { flex: 1 }, content: { padding: spacing.xl, paddingBottom: 48, gap: spacing.xl }, back: { color: colors.body, fontSize: 16 }, title: { color: colors.text, fontSize: 28, fontWeight: '800' }, subtitle: { marginTop: spacing.sm, color: colors.body, fontSize: 15, lineHeight: 22 }, form: { gap: spacing.lg }, sizeBlock: { gap: spacing.sm }, label: { color: colors.text, fontSize: 14, fontWeight: '600' }, sizeRow: { flexDirection: 'row', gap: spacing.sm }, sizeButton: { flex: 1, height: 48, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.surface }, sizeActive: { borderColor: colors.primary, backgroundColor: colors.primaryWeak }, sizeLabel: { color: colors.body, fontWeight: '600' }, sizeLabelActive: { color: colors.primary }, error: { color: colors.danger, fontSize: 14 } });
