import { useMemo, useState, type ReactNode } from 'react';
import { Image, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ArrowLeft, ChevronRight, Coffee, MapPin, PawPrint, Search, Trees, X } from 'lucide-react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ExplorerBrand, ExplorerGuide } from './ExplorerBrand';
import { colors } from '@/constants/theme';
import type { PetSpot } from '@/services/petTourService';

export function MapExplorer({ children, spots = [], web = false }: { children: ReactNode; spots?: PetSpot[]; web?: boolean }) {
  const [query, setQuery] = useState('');
  const [filter, setFilter] = useState('전체');
  const [selected, setSelected] = useState<PetSpot | null>(null);
  const visible = useMemo(() => spots.filter(spot => (!query || `${spot.title} ${spot.address}`.includes(query)) && (filter === '전체' || (filter === '음식점' ? spot.contentTypeId === '39' : ['12', '14', '15', '28'].includes(spot.contentTypeId)))), [spots, query, filter]);
  return <SafeAreaView edges={['top', 'left', 'right']} style={styles.screen}>
    <ExplorerBrand label="발자국 탐험 지도" />
    <View style={styles.search}><Search size={19} color={colors.body} /><TextInput accessibilityLabel="장소 검색" placeholder="어디로 떠나볼까요?" placeholderTextColor={colors.body} value={query} onChangeText={setQuery} style={styles.input} /></View>
    <View style={styles.filters}>{['전체', '관광지', '음식점'].map((label, i) => <Pressable key={label} accessibilityRole="button" accessibilityState={{ selected: filter === label }} onPress={() => setFilter(label)} style={[styles.chip, filter === label && styles.activeChip]}>{i === 1 ? <Trees size={15} color={colors.text} /> : i === 2 ? <Coffee size={15} color={colors.text} /> : <PawPrint size={15} color={colors.text} />}<Text style={styles.chipText}>{label}</Text></Pressable>)}</View>
    <View style={styles.map}>{children}</View>
    <View style={styles.discover}><View style={styles.discoverHeading}><View><Text style={styles.heading}>가까운 발자국 여행지</Text><Text style={styles.sub}>{web ? '안드로이드에서 위치 기반으로 탐험해요' : `내 주변 ${visible.length}곳 · 반려동물 동반 여행`}</Text></View><MapPin size={23} color={colors.primary} /></View>
      {visible.length ? <ScrollView style={styles.spotList} showsVerticalScrollIndicator={false}>{visible.map(spot => <Pressable key={spot.id} onPress={() => setSelected(spot)} style={styles.spot}><View style={styles.spotIcon}><PawPrint size={19} color={colors.primary} /></View><View style={styles.spotCopy}><Text numberOfLines={1} style={styles.spotTitle}>{spot.title}</Text><Text numberOfLines={1} style={styles.sub}>{spot.distance != null ? `${Math.round(spot.distance)}m · ` : ''}{spot.address}</Text></View><ChevronRight size={18} color={colors.body} /></Pressable>)}</ScrollView> : <ExplorerGuide title={query ? '다른 장소를 찾아볼까요?' : '반려견과 동네를 발견해요'} subtitle={web ? '지도와 캐릭터는 안드로이드 앱에서 표시됩니다.' : '주변 장소가 조회되면 여기에 표시돼요.'} />}
    </View>
    <Modal visible={!!selected} onRequestClose={() => setSelected(null)} animationType="slide"><SafeAreaView style={styles.screen}>{selected && <><View style={styles.detailHeading}><Pressable accessibilityLabel="장소 상세 닫기" onPress={() => setSelected(null)}><ArrowLeft size={24} color={colors.text} /></Pressable><Text style={styles.heading}>탐험 장소</Text><Pressable accessibilityLabel="닫기" onPress={() => setSelected(null)}><X size={22} color={colors.text} /></Pressable></View><ScrollView contentContainerStyle={styles.detail}>{selected.image ? <Image source={{ uri: selected.image }} style={styles.photo} /> : <View style={styles.noPhoto}><PawPrint size={60} color={colors.primary} /><Text style={styles.sub}>등록된 사진이 없어요</Text></View>}<Text style={styles.placeTitle}>{selected.title}</Text><Text style={styles.sub}>{selected.address}</Text>{selected.distance != null && <Text style={styles.distance}>현재 위치에서 약 {Math.round(selected.distance)}m</Text>}<View style={styles.info}><Text style={styles.heading}>반려견 동반 안내</Text><Text style={styles.infoText}>이용 조건 확인 필요</Text><Text style={styles.sub}>실내 이용과 동반 조건은 방문 전에 시설에 확인해 주세요.</Text>{selected.tel && <Text style={styles.infoText}>문의 · {selected.tel}</Text>}</View><ExplorerGuide title="다음 발자국을 남겨요" subtitle="함께 방문한 순간을 여행 기록에 남겨보세요." /><Pressable style={styles.cta} onPress={() => setSelected(null)}><Text style={styles.ctaText}>탐험 지도로 돌아가기</Text></Pressable></ScrollView></>}</SafeAreaView></Modal>
  </SafeAreaView>;
}
const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.canvas }, search: { marginHorizontal: 20, flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#F0F3EE', borderRadius: 28, paddingHorizontal: 16, minHeight: 46 }, input: { flex: 1, minWidth: 0, color: colors.text, fontSize: 14, paddingVertical: 12 }, filters: { flexDirection: 'row', gap: 8, paddingHorizontal: 20, paddingVertical: 12 }, chip: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 16, paddingVertical: 10, backgroundColor: '#F0F3EE', borderRadius: 24 }, activeChip: { backgroundColor: colors.primaryFill }, chipText: { fontSize: 12, fontWeight: '700', color: colors.onPrimary }, map: { flex: 1, minHeight: 130, overflow: 'hidden', marginHorizontal: 12, borderRadius: 24, backgroundColor: '#E9EEE2' }, discover: { paddingTop: 18, paddingBottom: 80, borderTopLeftRadius: 28, borderTopRightRadius: 28, backgroundColor: colors.surface, marginTop: -12 }, discoverHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 22 }, heading: { color: colors.text, fontSize: 18, fontWeight: '800' }, sub: { color: colors.body, fontSize: 12, lineHeight: 19, marginTop: 4 }, spotList: { maxHeight: 150, marginHorizontal: 20, marginTop: 12 }, spot: { paddingVertical: 12, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderColor: colors.border }, spotIcon: { width: 42, height: 42, borderRadius: 16, backgroundColor: colors.primaryWeak, alignItems: 'center', justifyContent: 'center' }, spotCopy: { flex: 1 }, spotTitle: { color: colors.text, fontSize: 14, fontWeight: '700' }, detailHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 20 }, detail: { padding: 20, gap: 16, maxWidth: 480, width: '100%', alignSelf: 'center' }, photo: { width: '100%', height: 240, borderRadius: 24 }, noPhoto: { height: 220, backgroundColor: colors.primaryWeak, borderRadius: 24, alignItems: 'center', justifyContent: 'center' }, placeTitle: { color: colors.text, fontSize: 28, fontWeight: '800' }, distance: { color: colors.primary, fontSize: 14, fontWeight: '600' }, info: { padding: 20, borderRadius: 24, backgroundColor: colors.primaryWeak, gap: 8 }, infoText: { color: colors.primary, fontWeight: '700', fontSize: 14 }, cta: { backgroundColor: colors.primaryFill, padding: 18, borderRadius: 24, alignItems: 'center' }, ctaText: { color: colors.onPrimary, fontWeight: '700' },
});
