import { Clock, ImageIcon, FileText, MapPin } from 'lucide-react-native';
import { Image, StyleSheet, Text, View } from 'react-native';
import { colors } from '@/constants/theme';
import type { TimelineActivity } from '@/types/record';

export function TravelRecordList({ activities }: { activities: TimelineActivity[] }) {
  return <View style={styles.list}><View style={styles.summary}><ImageIcon size={18} color={colors.primary} /><Text style={styles.summaryText}>오늘의 추억 {activities.length}개</Text></View>{activities.length ? activities.map(activity => <View key={activity.id} style={styles.card}>{activity.imageUrl ? <Image source={typeof activity.imageUrl === 'string' ? { uri: activity.imageUrl } : activity.imageUrl} style={styles.photo} resizeMode="cover" /> : null}<View style={styles.copy}><View style={styles.heading}><Text style={styles.title}>{activity.title}</Text><Text style={styles.category}>{activity.category}</Text></View><View style={styles.meta}><Clock size={13} color={colors.body} /><Text style={styles.metaText}>{activity.time}</Text>{activity.location ? <><MapPin size={13} color={colors.body} /><Text numberOfLines={1} style={styles.location}>{activity.location}</Text></> : null}</View>{activity.description ? <Text style={styles.description}>{activity.description}</Text> : null}</View></View>) : <View style={styles.empty}><View style={styles.emptyIcon}><FileText size={30} color={colors.primary} /></View><Text style={styles.emptyTitle}>첫 추억을 남겨보세요</Text><Text style={styles.emptyText}>반려견과 함께한 순간을 기록해 보세요.</Text></View>}</View>;
}
const styles = StyleSheet.create({ list: { gap: 12, paddingHorizontal: 20 }, summary: { flexDirection: 'row', gap: 9, padding: 16, borderRadius: 16, backgroundColor: colors.primaryWeak, alignItems: 'center' }, summaryText: { fontSize: 14, fontWeight: '700', color: colors.text }, card: { borderWidth: 1, borderColor: colors.border, borderRadius: 20, overflow: 'hidden', backgroundColor: colors.surface }, photo: { width: '100%', height: 170 }, copy: { padding: 15, gap: 8 }, heading: { flexDirection: 'row', alignItems: 'center', gap: 10 }, title: { flex: 1, fontSize: 16, fontWeight: '700', color: colors.text }, category: { color: colors.primary, fontSize: 11, backgroundColor: colors.primaryWeak, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 }, meta: { flexDirection: 'row', alignItems: 'center', gap: 5 }, metaText: { fontSize: 12, color: colors.body }, location: { flex: 1, color: colors.body, fontSize: 12 }, description: { fontSize: 13, lineHeight: 21, color: colors.body }, empty: { alignItems: 'center', paddingVertical: 48, gap: 12 }, emptyIcon: { backgroundColor: colors.primaryWeak, padding: 18, borderRadius: 24 }, emptyTitle: { fontSize: 18, fontWeight: '700', color: colors.text }, emptyText: { fontSize: 13, color: colors.body } });
