import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { ChevronRight, Check } from 'lucide-react-native';
import { MissionProgressBar } from './MissionProgressBar';
import { MissionCategoryIcon } from './MissionSymbol';
import { missionColors as c } from '@/constants/missionTheme';
import { formatMissionProgress, getMissionProgressRatio, getMissionStatus } from '@/features/missions/missionUtils';
import type { Mission } from '@/types/mission';

export function MissionCard({ mission, isCompleting, onPress, onComplete }: { mission: Mission; isCompleting: boolean; onPress: () => void; onComplete: () => void }) {
  const status = getMissionStatus(mission), progress = formatMissionProgress(mission);
  return <View style={styles.card}><Pressable accessibilityRole="button" accessibilityLabel={`${mission.title}, ${progress}, 상세 보기`} onPress={onPress} style={styles.main}><MissionCategoryIcon category={mission.category} /><View style={styles.copy}><Text style={styles.title}>{mission.title}</Text><Text style={styles.progress}>{progress}</Text><MissionProgressBar value={getMissionProgressRatio(mission)} accessibilityLabel={`${mission.title} 진행률`} color={c.primaryFill} /><Text style={styles.meta}>{mission.deadlineLabel}</Text></View><View style={styles.view}><Text style={styles.viewText}>보기</Text><ChevronRight size={13} color={c.primary} /></View></Pressable><View style={styles.footer}>{status !== 'inProgress' ? <View style={styles.done}><Check size={14} color={c.success} /><Text style={styles.doneText}>미션 완료</Text></View> : <Pressable accessibilityRole="button" accessibilityLabel={`${mission.title} 완료하기`} disabled={isCompleting} onPress={onComplete} style={[styles.action, isCompleting && styles.disabled]}>{isCompleting ? <ActivityIndicator size="small" color={c.primary} /> : <Text style={styles.actionText}>완료하기</Text>}</Pressable>}</View></View>;
}
const styles = StyleSheet.create({ card: { borderWidth: 1, borderColor: c.border, borderRadius: 20, backgroundColor: c.card, overflow: 'hidden' }, main: { padding: 18, flexDirection: 'row', alignItems: 'center', gap: 14 }, copy: { flex: 1, minWidth: 0, gap: 7 }, title: { fontSize: 16, lineHeight: 23, fontWeight: '700', color: c.foreground }, progress: { fontSize: 13, color: c.body }, meta: { fontSize: 11, color: c.muted }, view: { borderWidth: 1, borderColor: c.border, borderRadius: 12, minHeight: 38, paddingHorizontal: 10, flexDirection: 'row', alignItems: 'center', gap: 2 }, viewText: { fontSize: 13, color: c.primary }, footer: { alignItems: 'flex-end', paddingHorizontal: 18, paddingBottom: 12 }, action: { backgroundColor: c.primaryWeak, paddingHorizontal: 13, paddingVertical: 9, borderRadius: 10 }, actionText: { fontSize: 12, fontWeight: '700', color: c.primary }, disabled: { opacity: 0.5 }, done: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: c.successWeak, padding: 8, borderRadius: 10 }, doneText: { fontSize: 11, color: c.success, fontWeight: '600' } });
